STANDARD_CUSTOM_FIELDS = {
	"Work Order": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "planned_start_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_source",
			"label": "APS Source",
			"fieldtype": "Data",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_required_delivery_date",
			"label": "APS Required Delivery Date",
			"fieldtype": "Date",
			"insert_after": "custom_aps_source",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_is_urgent",
			"label": "APS Urgent",
			"fieldtype": "Check",
			"insert_after": "custom_aps_required_delivery_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_status",
			"label": "APS Release Status",
			"fieldtype": "Select",
			"options": "\nPending\nPlanned\nSynced\nReleased\nLocked\nSkipped",
			"insert_after": "custom_aps_is_urgent",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_locked_for_reschedule",
			"label": "APS Locked For Reschedule",
			"fieldtype": "Check",
			"insert_after": "custom_aps_release_status",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_schedule_reference",
			"label": "APS Schedule Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_locked_for_reschedule",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_result_reference",
			"label": "APS Result Reference",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_schedule_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_commitment",
			"label": "APS Demand Commitment",
			"fieldtype": "Link",
			"options": "APS Demand Commitment",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Demand ownership and supply commitment managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_proposal_batch",
			"label": "APS Proposal Batch",
			"fieldtype": "Link",
			"options": "APS Work Order Proposal Batch",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_replan_cycle",
			"label": "APS Replan Cycle",
			"fieldtype": "Link",
			"options": "APS Replan Cycle",
			"insert_after": "custom_aps_proposal_batch",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Shift-replan lineage managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_campaign",
			"label": "APS Production Campaign",
			"fieldtype": "Link",
			"options": "APS Production Campaign",
			"insert_after": "custom_aps_replan_cycle",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Single-capacity-owner production campaign managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_output_role",
			"label": "APS Output Role",
			"fieldtype": "Select",
			"options": "\nPrimary\nCo-product",
			"insert_after": "custom_aps_campaign",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Output role inside an APS production campaign.",
		},
		{
			"fieldname": "custom_aps_capacity_owner",
			"label": "APS Capacity Owner",
			"fieldtype": "Data",
			"insert_after": "custom_aps_output_role",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Shared interval owner; co-product outputs never add capacity.",
		},
		{
			"fieldname": "custom_aps_source_reason",
			"label": "APS Source Reason",
			"fieldtype": "Small Text",
			"insert_after": "custom_aps_capacity_owner",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Auditable reason for APS-generated production supply.",
		},
	],
	"Work Order Scheduling": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "status",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_freeze_state",
			"label": "APS Freeze State",
			"fieldtype": "Select",
			"options": "\nOpen\nFrozen\nLocked",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_approval_state",
			"label": "APS Approval State",
			"fieldtype": "Select",
			"options": "\nPending\nApproved\nRejected",
			"insert_after": "custom_aps_freeze_state",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_batch",
			"label": "APS Release Batch",
			"fieldtype": "Link",
			"options": "APS Release Batch",
			"insert_after": "custom_aps_approval_state",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_replan_cycle",
			"label": "APS Replan Cycle",
			"fieldtype": "Link",
			"options": "APS Replan Cycle",
			"insert_after": "custom_aps_release_batch",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Applied shift-replan cycle managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_campaign",
			"label": "APS Production Campaign",
			"fieldtype": "Link",
			"options": "APS Production Campaign",
			"insert_after": "custom_aps_replan_cycle",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Production campaign represented by this scheduling document.",
		},
	],
	"Delivery Plan": [
		{
			"fieldname": "custom_aps_version",
			"label": "APS Version",
			"fieldtype": "Data",
			"insert_after": "remark",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_source",
			"label": "APS Source",
			"fieldtype": "Data",
			"insert_after": "custom_aps_version",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
	],
	"Delivery Plan Item Qty": [
		{
			"fieldname": "custom_aps_demand_identity",
			"label": "APS Demand Identity",
			"fieldtype": "Link",
			"options": "APS Demand Identity",
			"insert_after": "required_arrival_date",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Stable APS demand lineage; populated automatically when available.",
		},
		{
			"fieldname": "custom_aps_customer_schedule_item",
			"label": "APS Customer Schedule Item",
			"fieldtype": "Link",
			"options": "Customer Delivery Schedule Item",
			"insert_after": "custom_aps_demand_identity",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Current schedule revision row behind this delivery plan quantity.",
		},
		{
			"fieldname": "custom_aps_match_method",
			"label": "APS Match Method",
			"fieldtype": "Select",
			"options": "\nExplicit Identity\nSchedule Item\nSuggested\nUnallocated",
			"insert_after": "custom_aps_customer_schedule_item",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "How APS linked this delivery-plan quantity to demand.",
		},
	],
	"Delivery Plan Item": [
		{
			"fieldname": "custom_aps_demand_identity",
			"label": "APS Demand Identity",
			"fieldtype": "Link",
			"options": "APS Demand Identity",
			"insert_after": "so_detail",
			"allow_on_submit": 1,
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Demand lineage inherited from the delivery-plan quantity row.",
		},
		{
			"fieldname": "custom_aps_customer_schedule_item",
			"label": "APS Customer Schedule Item",
			"fieldtype": "Link",
			"options": "Customer Delivery Schedule Item",
			"insert_after": "custom_aps_demand_identity",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Current schedule revision row inherited from the delivery-plan quantity row.",
		},
		{
			"fieldname": "custom_aps_delivery_plan_qty",
			"label": "APS Delivery Plan Qty Row",
			"fieldtype": "Data",
			"insert_after": "custom_aps_customer_schedule_item",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Source Delivery Plan Item Qty row name.",
		},
		{
			"fieldname": "custom_aps_required_delivery_date",
			"label": "APS Required Delivery Date",
			"fieldtype": "Date",
			"insert_after": "custom_aps_delivery_plan_qty",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Required delivery date inherited from APS demand.",
		},
		{
			"fieldname": "custom_aps_match_method",
			"label": "APS Match Method",
			"fieldtype": "Select",
			"options": "\nExplicit Identity\nSchedule Item\nDelivery Plan FIFO\nSuggested\nUnallocated",
			"insert_after": "custom_aps_required_delivery_date",
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "How APS linked this allocated sales-order row to demand.",
		},
	],
	"Scheduling Item": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "remarks",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_result_reference",
			"label": "APS Result Reference",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_commitment",
			"label": "APS Demand Commitment",
			"fieldtype": "Link",
			"options": "APS Demand Commitment",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Demand ownership and supply commitment managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_segment_reference",
			"label": "APS Segment Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_shift_proposal",
			"label": "APS Shift Proposal",
			"fieldtype": "Link",
			"options": "APS Shift Schedule Proposal Batch",
			"insert_after": "custom_aps_segment_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_batch",
			"label": "APS Release Batch",
			"fieldtype": "Link",
			"options": "APS Release Batch",
			"insert_after": "custom_aps_shift_proposal",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_replan_cycle",
			"label": "APS Replan Cycle",
			"fieldtype": "Link",
			"options": "APS Replan Cycle",
			"insert_after": "custom_aps_release_batch",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Shift-replan lineage managed by Injection APS.",
		},
		{
			"fieldname": "custom_aps_campaign",
			"label": "APS Production Campaign",
			"fieldtype": "Link",
			"options": "APS Production Campaign",
			"insert_after": "custom_aps_replan_cycle",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Shared production campaign for this output.",
		},
		{
			"fieldname": "custom_aps_output_role",
			"label": "APS Output Role",
			"fieldtype": "Select",
			"options": "\nPrimary\nCo-product",
			"insert_after": "custom_aps_campaign",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Output role inside an APS production campaign.",
		},
		{
			"fieldname": "custom_aps_capacity_owner",
			"label": "APS Capacity Owner",
			"fieldtype": "Data",
			"insert_after": "custom_aps_output_role",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Single scheduling interval that owns machine and mold capacity.",
		},
	],
	"Stock Entry": [
		{
			"fieldname": "custom_aps_scheduling_item",
			"label": "APS Scheduling Item",
			"fieldtype": "Link",
			"options": "Scheduling Item",
			"insert_after": "work_order_scheduling",
			"no_copy": 1,
			"description": "Direct execution-detail source used by Injection APS.",
		},
		{
			"fieldname": "custom_aps_segment_reference",
			"label": "APS Segment Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_scheduling_item",
			"fetch_from": "custom_aps_scheduling_item.custom_aps_segment_reference",
			"fetch_if_empty": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_output_type",
			"label": "APS Output Type",
			"fieldtype": "Select",
			"options": "\nGood\nScrap",
			"insert_after": "custom_aps_segment_reference",
			"no_copy": 1,
			"description": "Explicitly identifies accepted or scrap manufacture output.",
		},
	],
	"Delivery Note Item": [
		{
			"fieldname": "custom_aps_customer_schedule_item",
			"label": "APS Customer Schedule Item",
			"fieldtype": "Link",
			"options": "Customer Delivery Schedule Item",
			"insert_after": "so_detail",
			"allow_on_submit": 1,
			"no_copy": 1,
			"description": "Preferred direct customer-schedule allocation target for Injection APS.",
		},
		{
			"fieldname": "custom_aps_demand_identity",
			"label": "APS Demand Identity",
			"fieldtype": "Link",
			"options": "APS Demand Identity",
			"insert_after": "custom_aps_customer_schedule_item",
			"allow_on_submit": 1,
			"hidden": 1,
			"no_copy": 1,
			"description": "Preferred stable APS delivery-allocation target.",
		},
		{
			"fieldname": "custom_aps_delivery_plan_detail",
			"label": "APS Delivery Plan Detail",
			"fieldtype": "Data",
			"insert_after": "custom_aps_demand_identity",
			"allow_on_submit": 1,
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Delivery Plan Item row used to inherit APS demand lineage.",
		},
		{
			"fieldname": "custom_aps_match_method",
			"label": "APS Match Method",
			"fieldtype": "Select",
			"options": "\nExplicit Identity\nDelivery Plan\nSchedule Item\nLegacy Controlled Match\nUnallocated\nReturn Trace",
			"insert_after": "custom_aps_delivery_plan_detail",
			"allow_on_submit": 1,
			"hidden": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "How APS linked this delivery note row without changing ERPNext fulfillment.",
		},
	],
	"Item": [
		{
			"fieldname": "custom_aps_planning_section",
			"label": "APS Planning Parameters",
			"fieldtype": "Section Break",
			"insert_after": "manufacturing",
			"collapsible": 1,
		},
		{
			"fieldname": "custom_aps_prebuild_allowed",
			"label": "APS Prebuild Allowed",
			"fieldtype": "Check",
			"default": "1",
			"insert_after": "custom_aps_planning_section",
			"description": "Allows finished-goods production before the JIT window.",
		},
		{
			"fieldname": "custom_aps_max_prebuild_days",
			"label": "APS Max Prebuild Days",
			"fieldtype": "Int",
			"insert_after": "custom_aps_prebuild_allowed",
			"description": "Zero uses the APS Settings default.",
		},
		{
			"fieldname": "custom_aps_cancellation_risk_percent",
			"label": "APS Cancellation Risk Percent",
			"fieldtype": "Percent",
			"insert_after": "custom_aps_max_prebuild_days",
		},
		{
			"fieldname": "custom_aps_max_stock_qty",
			"label": "APS Max Stock Qty",
			"fieldtype": "Float",
			"non_negative": 1,
			"insert_after": "custom_aps_cancellation_risk_percent",
			"description": "Maximum finished-goods quantity for this item. Zero means no item-specific limit.",
		},
	],
	"Warehouse": [
		{
			"fieldname": "custom_aps_capacity_qty",
			"label": "APS Capacity Qty",
			"fieldtype": "Float",
			"non_negative": 1,
			"insert_after": "is_group",
			"description": "APS finished-goods capacity guard. Zero means no configured quantity limit.",
		},
	],
}

APS_OWNED_PAGE_NAMES = [
	"aps-schedule-console",
	"aps-customer-schedule-progress",
	"aps-net-requirement-workbench",
	"aps-demand-admission-workbench",
	"aps-constraint-resolution-center",
	"aps-solver-scenario-comparison",
	"aps-shift-replan-center",
	"aps-run-console",
	"aps-schedule-gantt",
	"aps-release-center",
]

APS_OWNED_RECORDS = {
	"Workspace": ["Injection APS"],
	"Custom HTML Block": ["Injection APS Dashboard"],
	"Page": APS_OWNED_PAGE_NAMES,
}


def get_standard_custom_field_names():
	names = []
	for doctype, fields in STANDARD_CUSTOM_FIELDS.items():
		for field in fields:
			names.append(f"{doctype}-{field['fieldname']}")
	return names
