STANDARD_CUSTOM_FIELDS = {
	"Work Order": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "planned_start_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_source",
			"label": "APS Source",
			"fieldtype": "Data",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_required_delivery_date",
			"label": "APS Required Delivery Date",
			"fieldtype": "Date",
			"insert_after": "custom_aps_source",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_is_urgent",
			"label": "APS Urgent",
			"fieldtype": "Check",
			"insert_after": "custom_aps_required_delivery_date",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_status",
			"label": "APS Release Status",
			"fieldtype": "Select",
			"options": "\nPending\nPlanned\nSynced\nReleased\nLocked\nSkipped",
			"insert_after": "custom_aps_is_urgent",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_locked_for_reschedule",
			"label": "APS Locked For Reschedule",
			"fieldtype": "Check",
			"insert_after": "custom_aps_release_status",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_schedule_reference",
			"label": "APS Schedule Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_locked_for_reschedule",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_result_reference",
			"label": "APS Result Reference",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_schedule_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_proposal_batch",
			"label": "APS Proposal Batch",
			"fieldtype": "Link",
			"options": "APS Work Order Proposal Batch",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
	],
	"Work Order Scheduling": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "status",
			"allow_on_submit": 1,
			"read_only": 1,
			"in_list_view": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_freeze_state",
			"label": "APS Freeze State",
			"fieldtype": "Select",
			"options": "\nOpen\nFrozen\nLocked",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_approval_state",
			"label": "APS Approval State",
			"fieldtype": "Select",
			"options": "\nPending\nApproved\nRejected",
			"insert_after": "custom_aps_freeze_state",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_batch",
			"label": "APS Release Batch",
			"fieldtype": "Link",
			"options": "APS Release Batch",
			"insert_after": "custom_aps_approval_state",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
	],
	"Delivery Plan": [
		{
			"fieldname": "custom_aps_version",
			"label": "APS Version",
			"fieldtype": "Data",
			"insert_after": "remark",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_source",
			"label": "APS Source",
			"fieldtype": "Data",
			"insert_after": "custom_aps_version",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
	],
	"Scheduling Item": [
		{
			"fieldname": "custom_aps_run",
			"label": "APS Run",
			"fieldtype": "Link",
			"options": "APS Planning Run",
			"insert_after": "remarks",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_result_reference",
			"label": "APS Result Reference",
			"fieldtype": "Link",
			"options": "APS Schedule Result",
			"insert_after": "custom_aps_run",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_segment_reference",
			"label": "APS Segment Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_result_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_shift_proposal",
			"label": "APS Shift Proposal",
			"fieldtype": "Link",
			"options": "APS Shift Schedule Proposal Batch",
			"insert_after": "custom_aps_segment_reference",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_release_batch",
			"label": "APS Release Batch",
			"fieldtype": "Link",
			"options": "APS Release Batch",
			"insert_after": "custom_aps_shift_proposal",
			"allow_on_submit": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
	],
	"Stock Entry": [
		{
			"fieldname": "custom_aps_scheduling_item",
			"label": "APS Scheduling Item",
			"fieldtype": "Link",
			"options": "Scheduling Item",
			"insert_after": "work_order_scheduling",
			"no_copy": 1,
			"description": "Direct execution-detail source used by Injection APS.",
		},
		{
			"fieldname": "custom_aps_segment_reference",
			"label": "APS Segment Reference",
			"fieldtype": "Data",
			"insert_after": "custom_aps_scheduling_item",
			"fetch_from": "custom_aps_scheduling_item.custom_aps_segment_reference",
			"fetch_if_empty": 1,
			"read_only": 1,
			"no_copy": 1,
			"description": "Owned by Injection APS.",
		},
		{
			"fieldname": "custom_aps_output_type",
			"label": "APS Output Type",
			"fieldtype": "Select",
			"options": "\nGood\nScrap",
			"insert_after": "custom_aps_segment_reference",
			"no_copy": 1,
			"description": "Explicitly identifies accepted or scrap manufacture output.",
		},
	],
	"Delivery Note Item": [
		{
			"fieldname": "custom_aps_customer_schedule_item",
			"label": "APS Customer Schedule Item",
			"fieldtype": "Link",
			"options": "Customer Delivery Schedule Item",
			"insert_after": "so_detail",
			"no_copy": 1,
			"description": "Preferred direct customer-schedule allocation target for Injection APS.",
		},
	],
	"Item": [
		{
			"fieldname": "custom_aps_prebuild_allowed",
			"label": "APS Prebuild Allowed",
			"fieldtype": "Check",
			"default": "1",
			"insert_after": "shelf_life_in_days",
			"description": "Allows finished-goods production before the JIT window.",
		},
		{
			"fieldname": "custom_aps_max_prebuild_days",
			"label": "APS Max Prebuild Days",
			"fieldtype": "Int",
			"insert_after": "custom_aps_prebuild_allowed",
			"description": "Zero uses the APS Settings default.",
		},
		{
			"fieldname": "custom_aps_cancellation_risk_percent",
			"label": "APS Cancellation Risk Percent",
			"fieldtype": "Percent",
			"insert_after": "custom_aps_max_prebuild_days",
		},
		{
			"fieldname": "custom_aps_max_stock_qty",
			"label": "APS Max Stock Qty",
			"fieldtype": "Float",
			"non_negative": 1,
			"insert_after": "custom_aps_cancellation_risk_percent",
			"description": "Maximum finished-goods quantity for this item. Zero means no item-specific limit.",
		},
	],
	"Warehouse": [
		{
			"fieldname": "custom_aps_capacity_qty",
			"label": "APS Capacity Qty",
			"fieldtype": "Float",
			"non_negative": 1,
			"insert_after": "is_group",
			"description": "APS finished-goods capacity guard. Zero means no configured quantity limit.",
		},
	],
}

APS_OWNED_PAGE_NAMES = [
	"aps-schedule-console",
	"aps-customer-schedule-progress",
	"aps-net-requirement-workbench",
	"aps-run-console",
	"aps-schedule-gantt",
	"aps-release-center",
]

APS_OWNED_RECORDS = {
	"Workspace": ["Injection APS"],
	"Custom HTML Block": ["Injection APS Dashboard"],
	"Page": APS_OWNED_PAGE_NAMES,
}


def get_standard_custom_field_names():
	names = []
	for doctype, fields in STANDARD_CUSTOM_FIELDS.items():
		for field in fields:
			names.append(f"{doctype}-{field['fieldname']}")
	return names
